spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clubsocios
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: true

    spring:
      datasource:
        driverClassName=com:
          mysql:
            cj:
              jdbc:
                Driver: com.mysql.cj.jdbc.Driver


    database-platform=org:
      hibernate:
        dialect:
          MySQL5InnoDBDialect: org.hibernate.dialect.MySQL5InnoDBDialect


    spring.jpa.properties.jakarta.persitence.schema-generate.database.action: none
